import type { DirectAffiliateConfig, RetailerKey } from "./affiliateTypes";

/**
 * Only mark status "active" when you truly have a live direct affiliate setup.
 * Keep directLinkTemplate null until you have the real tracking wrapper from the network.
 *
 * Retailers NOT listed here will fall through to the aggregator (Skimlinks/Sovrn).
 */
export const directAffiliateOverrides: Partial<Record<RetailerKey, DirectAffiliateConfig>> = {
  // ── Mass-market & fast fashion ──────────────────────────────
  shein: {
    retailer: "shein",
    displayName: "SHEIN",
    status: "manual_review",
    countrySupport: ["US", "CA", "UK", "AU"],
    notes: "ShareASale program exists. TODO: apply and get deep-link template.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  zara: {
    retailer: "zara",
    displayName: "Zara",
    status: "manual_review",
    countrySupport: ["US", "CA", "UK"],
    notes: "Ambassador/affiliate program exists but invite-based. TODO: apply.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  hm: {
    retailer: "hm",
    displayName: "H&M",
    status: "manual_review",
    countrySupport: ["US", "CA", "UK", "AU"],
    notes: "Rakuten program. TODO: join and configure deep-link template.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  gap: {
    retailer: "gap",
    displayName: "Gap",
    status: "manual_review",
    countrySupport: ["US", "CA"],
    notes: "Rakuten program. TODO: join and configure.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  old_navy: {
    retailer: "old_navy",
    displayName: "Old Navy",
    status: "manual_review",
    countrySupport: ["US", "CA"],
    notes: "CJ Affiliate program. TODO: apply.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  banana_republic: {
    retailer: "banana_republic",
    displayName: "Banana Republic",
    status: "manual_review",
    countrySupport: ["US", "CA"],
    notes: "CJ Affiliate program. TODO: apply.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  uniqlo: {
    retailer: "uniqlo",
    displayName: "UNIQLO",
    status: "manual_review",
    countrySupport: ["US", "CA"],
    notes: "Rakuten program. TODO: verify and join.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  mango: {
    retailer: "mango",
    displayName: "Mango",
    status: "manual_review",
    countrySupport: ["US", "CA", "UK", "EU"],
    notes: "Awin program. TODO: apply.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  forever_21: {
    retailer: "forever_21",
    displayName: "Forever 21",
    status: "manual_review",
    countrySupport: ["US"],
    notes: "CJ program. TODO: apply.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  boohoo: {
    retailer: "boohoo",
    displayName: "Boohoo",
    status: "manual_review",
    countrySupport: ["US", "CA", "UK"],
    notes: "Awin program. TODO: apply.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  prettylittlething: {
    retailer: "prettylittlething",
    displayName: "PrettyLittleThing",
    status: "manual_review",
    countrySupport: ["US", "CA", "UK"],
    notes: "Awin program. TODO: apply.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  fashion_nova: {
    retailer: "fashion_nova",
    displayName: "Fashion Nova",
    status: "manual_review",
    countrySupport: ["US", "CA"],
    notes: "ShareASale program. TODO: apply.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  target: {
    retailer: "target",
    displayName: "Target",
    status: "manual_review",
    countrySupport: ["US"],
    notes: "Impact program. TODO: apply.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },

  // ── Department & multi-brand ────────────────────────────────
  nordstrom: {
    retailer: "nordstrom",
    displayName: "Nordstrom",
    status: "manual_review",
    countrySupport: ["US", "CA"],
    notes: "Rakuten program. TODO: join.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  asos: {
    retailer: "asos",
    displayName: "ASOS",
    status: "manual_review",
    countrySupport: ["US", "CA", "UK", "AU"],
    notes: "Awin program. TODO: apply.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  revolve: {
    retailer: "revolve",
    displayName: "Revolve",
    status: "manual_review",
    countrySupport: ["US", "CA"],
    notes: "CJ program. TODO: apply.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  amazon_fashion: {
    retailer: "amazon_fashion",
    displayName: "Amazon Fashion",
    status: "manual_review",
    countrySupport: ["US", "CA", "UK", "AU"],
    notes: "Amazon Associates. TODO: join and use tag param.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  urban_outfitters: {
    retailer: "urban_outfitters",
    displayName: "Urban Outfitters",
    status: "manual_review",
    countrySupport: ["US", "CA"],
    notes: "Rakuten program. TODO: join.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  abercrombie: {
    retailer: "abercrombie",
    displayName: "Abercrombie & Fitch",
    status: "manual_review",
    countrySupport: ["US", "CA"],
    notes: "CJ program. TODO: apply.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  jcrew: {
    retailer: "jcrew",
    displayName: "J.Crew",
    status: "manual_review",
    countrySupport: ["US", "CA"],
    notes: "CJ program. TODO: apply.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },

  // ── Athletic & activewear ───────────────────────────────────
  nike: {
    retailer: "nike",
    displayName: "Nike",
    status: "manual_review",
    countrySupport: ["US", "CA", "UK", "AU"],
    notes: "Impact program. TODO: apply.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  adidas: {
    retailer: "adidas",
    displayName: "Adidas",
    status: "manual_review",
    countrySupport: ["US", "CA", "UK", "AU"],
    notes: "Impact program. TODO: apply.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  puma: {
    retailer: "puma",
    displayName: "Puma",
    status: "manual_review",
    countrySupport: ["US", "CA"],
    notes: "CJ program. TODO: apply.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  lululemon: {
    retailer: "lululemon",
    displayName: "Lululemon",
    status: "manual_review",
    countrySupport: ["US", "CA"],
    notes: "Impact program. TODO: apply.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },

  // ── Luxury (with programs) ──────────────────────────────────
  burberry: {
    retailer: "burberry",
    displayName: "Burberry",
    status: "manual_review",
    countrySupport: ["US", "CA", "UK"],
    notes: "Rakuten program. TODO: verify and join.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  versace: {
    retailer: "versace",
    displayName: "Versace",
    status: "manual_review",
    countrySupport: ["US", "CA"],
    notes: "CJ program. TODO: verify and join.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },

  // ── DTC & specialty ─────────────────────────────────────────
  fabletics: {
    retailer: "fabletics",
    displayName: "Fabletics",
    status: "manual_review",
    countrySupport: ["US", "CA"],
    notes: "CJ program. TODO: apply.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  kith: {
    retailer: "kith",
    displayName: "Kith",
    status: "manual_review",
    countrySupport: ["US"],
    notes: "In-house referral program. TODO: apply.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  reformation: {
    retailer: "reformation",
    displayName: "Reformation",
    status: "manual_review",
    countrySupport: ["US", "CA"],
    notes: "ShareASale program. TODO: apply.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  gymshark: {
    retailer: "gymshark",
    displayName: "Gymshark",
    status: "manual_review",
    countrySupport: ["US", "CA", "UK"],
    notes: "Awin program. TODO: apply.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  alo_yoga: {
    retailer: "alo_yoga",
    displayName: "Alo Yoga",
    status: "manual_review",
    countrySupport: ["US", "CA"],
    notes: "ShareASale program. TODO: apply.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  everlane: {
    retailer: "everlane",
    displayName: "Everlane",
    status: "manual_review",
    countrySupport: ["US", "CA"],
    notes: "Pepperjam program. TODO: apply.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  cos: {
    retailer: "cos",
    displayName: "COS",
    status: "manual_review",
    countrySupport: ["US", "CA", "UK"],
    notes: "Awin program. TODO: apply.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  allsaints: {
    retailer: "allsaints",
    displayName: "AllSaints",
    status: "manual_review",
    countrySupport: ["US", "CA", "UK"],
    notes: "Awin program. TODO: apply.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  free_people: {
    retailer: "free_people",
    displayName: "Free People",
    status: "manual_review",
    countrySupport: ["US", "CA"],
    notes: "Rakuten program. TODO: join.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  vuori: {
    retailer: "vuori",
    displayName: "Vuori",
    status: "manual_review",
    countrySupport: ["US", "CA"],
    notes: "AvantLink program. TODO: apply.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  skims: {
    retailer: "skims",
    displayName: "SKIMS",
    status: "manual_review",
    countrySupport: ["US", "CA"],
    notes: "ShareASale program. TODO: apply.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  aritzia: {
    retailer: "aritzia",
    displayName: "Aritzia",
    status: "manual_review",
    countrySupport: ["US", "CA"],
    notes: "Rakuten program. TODO: join.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  carhartt: {
    retailer: "carhartt",
    displayName: "Carhartt",
    status: "manual_review",
    countrySupport: ["US", "CA"],
    notes: "AvantLink program. TODO: apply.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  vans: {
    retailer: "vans",
    displayName: "Vans",
    status: "manual_review",
    countrySupport: ["US", "CA"],
    notes: "CJ program. TODO: apply.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  converse: {
    retailer: "converse",
    displayName: "Converse",
    status: "manual_review",
    countrySupport: ["US", "CA"],
    notes: "CJ program. TODO: apply.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  dr_martens: {
    retailer: "dr_martens",
    displayName: "Dr. Martens",
    status: "manual_review",
    countrySupport: ["US", "CA", "UK"],
    notes: "Awin program. TODO: apply.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  birkenstock: {
    retailer: "birkenstock",
    displayName: "Birkenstock",
    status: "manual_review",
    countrySupport: ["US", "CA", "UK"],
    notes: "Awin program. TODO: apply.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  on_running: {
    retailer: "on_running",
    displayName: "On",
    status: "manual_review",
    countrySupport: ["US", "CA"],
    notes: "Awin program. TODO: apply.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  hoka: {
    retailer: "hoka",
    displayName: "HOKA",
    status: "manual_review",
    countrySupport: ["US", "CA"],
    notes: "CJ program. TODO: apply.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  anthropologie: {
    retailer: "anthropologie",
    displayName: "Anthropologie",
    status: "manual_review",
    countrySupport: ["US", "CA"],
    notes: "Rakuten program. TODO: join.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },

  // ── Multi-brand luxury aggregators (fallback candidates) ────
  ssense: {
    retailer: "ssense",
    displayName: "SSENSE",
    status: "manual_review",
    countrySupport: ["US", "CA", "UK", "EU"],
    notes: "Good luxury fallback. TODO: apply for direct program.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
  farfetch: {
    retailer: "farfetch",
    displayName: "Farfetch",
    status: "manual_review",
    countrySupport: ["US", "CA", "UK", "EU"],
    notes: "Good luxury fallback. TODO: apply for direct program.",
    lastVerifiedAt: "2026-03-13",
    directLinkTemplate: null,
  },
};
