const RETAILERS: Record<string, string> = {
  // Fast fashion & mass market
  'zara': 'Zara',
  'hm': 'H&M',
  'shein': 'SHEIN',
  'uniqlo': 'Uniqlo',
  'mango': 'Mango',
  'fashionnova': 'Fashion Nova',
  'prettylittlething': 'PrettyLittleThing',
  'boohoo': 'Boohoo',
  'forever21': 'Forever 21',
  'primark': 'Primark',
  'bershka': 'Bershka',
  'pullandbear': 'Pull & Bear',
  'stradivarius': 'Stradivarius',
  'massimo': 'Massimo Dutti',
  'topshop': 'Topshop',
  'misguided': 'Missguided',
  'nastygal': 'Nasty Gal',
  'romwe': 'Romwe',
  'cider': 'Cider',
  'temu': 'Temu',

  // Department stores & multi-brand
  'nordstrom': 'Nordstrom',
  'macys': "Macy's",
  'bloomingdales': "Bloomingdale's",
  'saksfifthavenue': 'Saks',
  'saks': 'Saks',
  'neimanmarcus': 'Neiman Marcus',
  'jcpenney': 'JCPenney',
  'kohls': "Kohl's",
  'dillards': "Dillard's",
  'selfridges': 'Selfridges',
  'harrods': 'Harrods',
  'debenhams': 'Debenhams',
  'johnlewis': 'John Lewis',
  'houseoffraser': 'House of Fraser',
  'thebay': 'Hudson\'s Bay',

  // Online multi-brand
  'asos': 'ASOS',
  'revolve': 'Revolve',
  'farfetch': 'Farfetch',
  'ssense': 'SSENSE',
  'mrporter': 'Mr Porter',
  'net-a-porter': 'Net-a-Porter',
  'matchesfashion': 'Matches',
  'mytheresa': 'Mytheresa',
  'luisaviaroma': 'Luisaviaroma',
  'shopbop': 'Shopbop',
  'yoox': 'YOOX',
  '24s': '24S',
  'endclothing': 'END.',
  'sneakersnstuff': 'SNS',
  'dtlr': 'DTLR',
  'footlocker': 'Foot Locker',
  'finishline': 'Finish Line',
  'zappos': 'Zappos',

  // General & big box
  'amazon': 'Amazon',
  'target': 'Target',
  'walmart': 'Walmart',
  'costco': 'Costco',

  // Gap Inc.
  'gap': 'Gap',
  'oldnavy': 'Old Navy',
  'bananarepublic': 'Banana Republic',
  'athleta': 'Athleta',

  // A&F Corp & similar
  'abercrombie': 'Abercrombie',
  'hollister': 'Hollister',
  'americaneagle': 'American Eagle',
  'ae': 'American Eagle',
  'pacsun': 'PacSun',

  // J.Crew / preppy
  'jcrew': 'J.Crew',
  'brooksbrothers': 'Brooks Brothers',
  'ralphlauren': 'Ralph Lauren',
  'tommyhilfiger': 'Tommy Hilfiger',
  'calvinklein': 'Calvin Klein',
  'lacoste': 'Lacoste',

  // Urban / street / casual
  'urbanoutfitters': 'Urban Outfitters',
  'freepeople': 'Free People',
  'anthropologie': 'Anthropologie',
  'huf': 'HUF',
  'stussy': 'Stüssy',
  'supremenewyork': 'Supreme',
  'palace': 'Palace',
  'bape': 'BAPE',
  'kith': 'Kith',
  'fearofgod': 'Fear of God',
  'essentials': 'Essentials',

  // Activewear & sportswear
  'nike': 'Nike',
  'adidas': 'Adidas',
  'puma': 'Puma',
  'lululemon': 'Lululemon',
  'underarmour': 'Under Armour',
  'reebok': 'Reebok',
  'newbalance': 'New Balance',
  'asics': 'ASICS',
  'fila': 'FILA',
  'champion': 'Champion',
  'gymshark': 'Gymshark',
  'alo': 'Alo Yoga',
  'vuori': 'Vuori',
  'outdoorvoices': 'Outdoor Voices',
  'on-running': 'On',
  'hoka': 'HOKA',
  'salomon': 'Salomon',
  'theNorthface': 'The North Face',
  'thenorthface': 'The North Face',
  'patagonia': 'Patagonia',
  'columbia': 'Columbia',
  'arcteryx': "Arc'teryx",

  // Denim
  'levis': "Levi's",
  'levi': "Levi's",
  'wrangler': 'Wrangler',
  'diesel': 'Diesel',
  'trueReligion': 'True Religion',
  'agolde': 'AGOLDE',
  'citizensofhumanity': 'Citizens of Humanity',
  'frame': 'FRAME',
  'motherDenim': 'Mother',

  // Luxury fashion houses
  'gucci': 'Gucci',
  'louisvuitton': 'Louis Vuitton',
  'chanel': 'Chanel',
  'dior': 'Dior',
  'prada': 'Prada',
  'burberry': 'Burberry',
  'balenciaga': 'Balenciaga',
  'versace': 'Versace',
  'givenchy': 'Givenchy',
  'fendi': 'Fendi',
  'valentino': 'Valentino',
  'bottegaveneta': 'Bottega Veneta',
  'saintlaurent': 'Saint Laurent',
  'ysl': 'YSL',
  'celine': 'Celine',
  'loewe': 'Loewe',
  'alexandermcqueen': 'Alexander McQueen',
  'stellamccartney': 'Stella McCartney',
  'tomford': 'Tom Ford',
  'dolcegabbana': 'Dolce & Gabbana',
  'moncler': 'Moncler',
  'amiri': 'Amiri',
  'offwhite': 'Off-White',
  'jacquemus': 'Jacquemus',
  'isabelmarant': 'Isabel Marant',
  'acnestudios': 'Acne Studios',
  'maxmara': 'Max Mara',
  'marni': 'Marni',
  'jilsander': 'Jil Sander',
  'maison': 'Maison Margiela',
  'thom': 'Thom Browne',
  'rick': 'Rick Owens',
  'commedesgarcons': 'Comme des Garçons',
  'sacai': 'Sacai',

  // Watches & accessories
  'timex': 'Timex',
  'casio': 'Casio',
  'fossil': 'Fossil',
  'danielwellington': 'Daniel Wellington',
  'swatch': 'Swatch',
  'omega': 'Omega',
  'rolex': 'Rolex',
  'tagheuer': 'TAG Heuer',
  'tissot': 'Tissot',
  'cartier': 'Cartier',
  'tiffany': 'Tiffany & Co.',
  'pandora': 'Pandora',
  'swarovski': 'Swarovski',
  'mejuri': 'Mejuri',
  'kendrascott': 'Kendra Scott',
  'davidyurman': 'David Yurman',
  'rayban': 'Ray-Ban',
  'warbyparker': 'Warby Parker',

  // Resale & consignment
  'ebay': 'eBay',
  'depop': 'Depop',
  'grailed': 'Grailed',
  'therealreal': 'The RealReal',
  'vestiaire': 'Vestiaire',
  'poshmark': 'Poshmark',
  'thredup': 'ThredUp',
  'mercari': 'Mercari',
  'stockx': 'StockX',
  'goat': 'GOAT',

  // Canadian
  'aritzia': 'Aritzia',
  'simons': 'Simons',
  'roots': 'Roots',
  'frank': 'Frank And Oak',
  'lolë': 'Lolë',

  // Beauty / cosmetics (common in fashion URLs)
  'sephora': 'Sephora',
  'ulta': 'Ulta',

  // Other popular
  'cos': 'COS',
  'arket': 'ARKET',
  'everlane': 'Everlane',
  'reformation': 'Reformation',
  'allsaints': 'AllSaints',
  'tedBaker': 'Ted Baker',
  'tedbaker': 'Ted Baker',
  'reiss': 'Reiss',
  'superdry': 'Superdry',
  'scotch': 'Scotch & Soda',
  'hugoboss': 'Hugo Boss',
  'boss': 'BOSS',
  'armani': 'Armani',
  'michaelkors': 'Michael Kors',
  'coach': 'Coach',
  'katespade': 'Kate Spade',
  'toryburch': 'Tory Burch',
  'marcjacobs': 'Marc Jacobs',
  'kenzo': 'Kenzo',
  'carhartt': 'Carhartt',
  'dickies': 'Dickies',
  'vans': 'Vans',
  'converse': 'Converse',
  'birkenstock': 'Birkenstock',
  'drmartens': 'Dr. Martens',
  'crocs': 'Crocs',
  'ugg': 'UGG',
  'stuartweitzman': 'Stuart Weitzman',
  'jimmychoo': 'Jimmy Choo',
  'manoloblahnik': 'Manolo Blahnik',
  'louboutin': 'Louboutin',
  'skims': 'SKIMS',
  'savagexfenty': 'Savage X Fenty',
  'victoriassecret': "Victoria's Secret",
  'spanx': 'Spanx',
};

export function detectRetailer(url: string): string | null {
  try {
    const hostname = new URL(url).hostname.toLowerCase();
    for (const [key, label] of Object.entries(RETAILERS)) {
      if (hostname.includes(key)) return label;
    }
    return 'Shop';
  } catch {
    return null;
  }
}
