project_id = "omdfzenqosecrytezyfa"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.get-size-recommendation]
verify_jwt = false

[functions.scrape-size-charts]
verify_jwt = false

[functions.categorize-products]
verify_jwt = false
